### PR TITLE
Fixed ChannelMemoryBackend.Stop method 

### PR DESCRIPTION
**Pull request by zazab**
Without this fix it hangs if you use Stop

### CODE REVIEW

**Comment by giftig** [comment]
Why not just return instead of creating a label to break the loop? If you change the last line to a defer before the loop you'll ensure it's still called (and not have to worry about it again)

**Comment by zazab** [comment]
Yes, this way is more clear. Sorry for late response.

**Comment by giftig** [comment]
No worries; that looks good to me now.

**Comment by op** [comment]
Thanks!

**Pull request merged**
