### PR TITLE
Implement backend for the golang default logger

### PR DESCRIPTION
**Pull request by driskell**
I needed the ability to reopen the log file used by the logging subsystem without losing any logs.

It seems that the default golang logger allows us via the SetOutput exposed function. However, the exposed Logger structure does not have this as a method and there is no way I can see to change the output for an existing Logger. Thus, NewLogBackend is not able to switch the output for the purposes of reopening the log file.

This PR implements NewDefaultLogBackend, which rather than creating a Logger structure, simply defers to the default golang logger, and allows the SetOutput exposed function to be used to reopen the log file. I've simplified that process by providing a Reopen and a Close method.

I welcome your thoughts on usefulness of this, improvements, test requirements etc, and will also in due time propose to Golang to have their stdlib extended so that SetOutput is also a method on a logger. Though that won't be before 1.5/1.6 for sure and at least the method in this PR is compatible much further back.

Jason

### CODE REVIEW

**Comment by driskell** [comment]
Just pushed missing commit and squashed.

**Comment by op** [comment]
You can always take an alternative approach and implement the io.Writer interface and set it for both the default logger and use it in this library. There you can easily change the actually used output.

I don't quite understand why this is needed though.

**Comment by driskell** [comment]
If I use a io.Writer in this library it will defer to the Logger struct from the log library which uses a muted to synchronise writes from multiple routines.

I cannot close or reopen the file without then adding another layer of mutex - one which will only be required once a day. The SetOutput uses the Logger's internal mutex saving that extra hit.

I understand it's not ideal though - better would be if Logger struct actually had SetOutput but only the default one does :-(

**Comment by op** [comment]
I didn't meant to close this PR though.

**Comment by driskell** [comment]
@op Golang just implemented SetOutput for the Logger struct:

https://github.com/golang/go/issues/9629

Looks like it'll be available in Go 1.5

So I guess no need to have this PR here - once on Go 1.5 we'll be able to use a Logger struct as before and SetOuput. In the mean time though I'll keep this code snippet in my project as a temporary patch, and maybe as a backwards compatible code for Go <=1.4. I think a simple interface check for SetOutput can select between the two.

**Pull request closed without merging**
