### PR TITLE
Replaced MustGetLogger with more idiomatic GetLogger.

### PR DESCRIPTION
**Pull request by xavi-**
Also, +1 to renaming `GetLogger` to `NewLogger`.

### CODE REVIEW

**Comment by op** [comment]
Sorry, I don't agree. Why would this be more idiomatic?

**Comment by xavi-** [comment]
Panics aren't great.  They're very noisy and hard to recover from.  A returned error value is nicer to deal with.  Nearly ever method in the golang stdlib uses error values for error handling.  Here's a stackoverflow question that goes into more detail: http://stackoverflow.com/questions/21265464/golang-idiomatic-error-handling

**Comment by jaytaylor** [comment]
I also don't agree.  Full explanation would be needed for me to consider supporting this change.

**Comment by jaytaylor** [comment]
I have never even observed this go logging panic getting triggered IRL, so why is this worth everyone's time?  Are you hitting it a lot? Has it caused you significant trouble?

**Comment by op** [comment]
@xavi OK. I might have been a bit trigger happy.

Yes, I agree with you. I even see that I have a TODO about calling it `NewLogger`. However, since I don't feel like breaking backwards compatibility right now it will stay as is.

For the formatter, both versions are available there; use the `NewStringFormatter` if you want but in the example I believe it doesn't hurt to use the `Must` variant. If you however can change the format string from a configuration file or similar, I agree that you should use the `NewStringFormatter`.

The `New` vs. `Must` pattern is taken from the regexp package in this case.

**Comment by xavi-** [comment]
Yeah, the lack of semvar or similar mechanism makes golang a troublesome language...  An alternative is to make `NewLogger` an alias for `GetLogger` and deprecate `GetLogger`.

**Pull request closed without merging**
