### PR TITLE
Added Is<Level>Enabled methods for logger

### PR DESCRIPTION
**Pull request by d-ulyanov**

### CODE REVIEW

**Comment by op** [comment]
Which interface is this for?

**Comment by d-ulyanov** [comment]
My description wasn't correct - its not for interfaces compatibility at all :) 
These methods is very useful and all most popular logging libs provides it (log4j, log4php and other Apache libs, and not only apache :) )

**Comment by d-ulyanov** [comment]
@op could you accept this pull request?

**Comment by d-ulyanov** [comment]
up

**Comment by op** [comment]
I can see the usefulness but I believe the API just gets more cluttered with this. You can always keep these as helper methods in your own code. Thanks!

**Pull request closed without merging**
